easy app x86 + upgrade to node 6 + git portable x86

diff --git a/tools/git/mingw32/libexec/git-core/git-merge-octopus b/tools/git/mingw32/libexec/git-core/git-merge-octopus
--- a/tools/git/mingw32/libexec/git-core/git-merge-octopus
+++ b/tools/git/mingw32/libexec/git-core/git-merge-octopus
@@ -5,13 +5,10 @@
 # Resolve two or more trees.
 #
 
+. git-sh-setup
+
 LF='
 '
-
-die () {
-    echo >&2 "$*"
-    exit 1
-}
 
 # The first parameters up to -- are merge bases; the rest are heads.
 bases= head= remotes= sep_seen=
@@ -44,6 +41,12 @@ esac
 # MRC is the current "merge reference commit"
 # MRT is the current "merge result tree"
 
+if ! git diff-index --quiet --cached HEAD --
+then
+    gettextln "Error: Your local changes to the following files would be overwritten by merge"
+    git diff-index --cached --name-only HEAD -- | sed -e 's/^/    /'
+    exit 2
+fi
 MRC=$(git rev-parse --verify -q $head)
 MRT=$(git write-tree)
 NON_FF_MERGE=0
@@ -55,8 +58,8 @@ do
 		# We allow only last one to have a hand-resolvable
 		# conflicts.  Last round failed and we still had
 		# a head to merge.
-		echo "Automated merge did not work."
-		echo "Should not be doing an Octopus."
+		gettextln "Automated merge did not work."
+		gettextln "Should not be doing an Octopus."
 		exit 2
 	esac
 
@@ -67,13 +70,11 @@ do
 		eval pretty_name=\${GITHEAD_$SHA1_UP:-$pretty_name}
 	fi
 	common=$(git merge-base --all $SHA1 $MRC) ||
-		die "Unable to find common commit with $pretty_name"
+		die "$(eval_gettext "Unable to find common commit with \$pretty_name")"
 
 	case "$LF$common$LF" in
 	*"$LF$SHA1$LF"*)
-		cat << EOF
-Already up-to-date with $pretty_name
-EOF
+		eval_gettextln "Already up-to-date with \$pretty_name"
 		continue
 		;;
 	esac
@@ -85,9 +86,7 @@ EOF
 		# tree as the intermediate result of the merge.
 		# We still need to count this as part of the parent set.
 
-		cat << EOF
-Fast-forwarding to: $pretty_name
-EOF
+		eval_gettextln "Fast-forwarding to: \$pretty_name"
 		git read-tree -u -m $head $SHA1 || exit
 		MRC=$SHA1 MRT=$(git write-tree)
 		continue
@@ -95,14 +94,12 @@ EOF
 
 	NON_FF_MERGE=1
 
-	cat << EOF
-Trying simple merge with $pretty_name
-EOF
+	eval_gettextln "Trying simple merge with \$pretty_name"
 	git read-tree -u -m --aggressive  $common $MRT $SHA1 || exit 2
 	next=$(git write-tree 2>/dev/null)
 	if test $? -ne 0
 	then
-		echo "Simple merge did not work, trying automatic merge."
+		gettextln "Simple merge did not work, trying automatic merge."
 		git-merge-index -o git-merge-one-file -a ||
 		OCTOPUS_FAILURE=1
 		next=$(git write-tree 2>/dev/null)
